//Base de datos de carros de las principales marcas en el mundo

db.cars.insertMany([
  
  {marca: 'Toyota', modelo: 'GR Yaris 2024', añoFabricacion: 2020 , precio: 266000000, consumoCombustible: 8.7, color: 'Blanco', capacidadPasajeros: 4, tipoTransmision: 'Manual de 6 velocidades', potenciaMotor: 272, sistemaSeguridad: 'Control de velocidad crucero adaptativo (ACC),Sistema de pre-colisión frontal (PCS),Sistema de alerta de cambio de carril (LDA),Sistema de luces altas automáticas (AHB),Alerta de punto ciego (BSM),Alerta de tráfico trasero (RCTA),Alarma antirrobo e inmovilizador de motor,Asistente de frenado de emergencia (BA),etc.'},
  {marca: 'Volkswagen', modelo: 'Nivus', añoFabricacion: 2021, precio: 89990000, consumoCombustible: 7.1, color: 'Gris', capacidadPasajeros: 5, tipoTransmision: 'Automática de 6 velocidades', potenciaMotor: 94, sistemaSeguridad: 'seis airbags, frenos ABS + EBD, control electrónico de estabilidad (ESC), control de tracción (ASR), asistente de tracción dinámica en curvas (XDS), asistente de frenado de emergencia (HBA), cinturones de tres puntos en todas las posiciones, etc.'},
  {marca: 'Ford', modelo: 'Ranger Raptor', añoFabricacion: 1982, precio:  316289984, consumoCombustible: 13.8 , color: 'Naranja', capacidadPasajeros: 5, tipoTransmision: 'Transmisión automática de 10 velocidades', potenciaMotor: 288, sistemaSeguridad: '7 Airbags, Control de descenso, Asistente de Arranque en Pendiente (HLA), Control de Carga Adaptativo (LAC), Control Antivuelco (ROM) y Control de Balanceo de Trailer (TSM), Sensores de Parqueo Delanteros y Traseros'},
  {marca: 'Honda', modelo: 'Honda CR-V', añoFabricacion: 1995, precio: 164990000, consumoCombustible: 11.20, color: 'Azul', capacidadPasajeros: 5, tipoTransmision: 'Transmisión CVT con modo sport y low y Transmisión con modo sport y Paddle shift', potenciaMotor: 155, sistemaSeguridad: 'Honda Sensing 360'},
  {marca: 'Nissan', modelo: 'Pathfinder', añoFabricacion:1986 , precio: 257990000, consumoCombustible: 12.7, color: 'Verde', capacidadPasajeros: 8, tipoTransmision: 'Automática de 9 velocidades', potenciaMotor: 270, sistemaSeguridad: 'Bolsas de aire frontales,Bolsas de aire laterales y de cortina,Freno de,estacionamiento electrónico con Asistente de marcha detenida(AUTOHOLD),Control dinámico de vehículo (VDC),Asistente de ascenso en Pendientes (HSA),Sensores de parqueo frontales y traseros,Asistente de frenado de emergencia inteligente (IEB),Advertencia de abandono de carril (LDW), etc.'},
  {marca: 'Hyundai', modelo: 'Tucson', añoFabricacion: 2015, precio: 118990000, consumoCombustible: 12.45, color: 'Bronce', capacidadPasajeros: 5, tipoTransmision: 'Manual de 6 velocidades + reversa y Automática / Secuencial de 6 velocidades + reversa', potenciaMotor: 230, sistemaSeguridad: 'Bolsas de aire,Cinturón de seguridad,Apoyacabezas delanteros ajustables,Sistema ISOFIX,Seguro para niños en las puertas traseras'},
  {marca: 'Chevrolet', modelo: 'Onix Turbo HB', añoFabricacion: 2019, precio: 74200000, consumoCombustible: 8.1, color: 'Rojo', capacidadPasajeros: 5, tipoTransmision: 'Mecánica de 5 velocidades y Automática de 6 velocidades', potenciaMotor: 115 , sistemaSeguridad: 'Airbags,Control de estabilidad y tracción,Luz antiniebla trasera,ISOFIX,Cinturones de 3 puntas,Sistema keyless,Frenos ABS con EBD,Asistente de arranque en pendiente,etc.'},
  {marca: 'Kia', modelo: 'Picanto', añoFabricacion: 2004, precio: 54990000, consumoCombustible: 5.3, color: 'Plata', capacidadPasajeros: 5, tipoTransmision: 'transmisión mecánica de 5 velocidades o automática de 4', potenciaMotor: 66, sistemaSeguridad: 'Bolsas de aire, control de tracción, frenos ABS con EBD, anclaje ISOFIX y dirección asistida eléctricamente'},
  {marca: 'Renault', modelo: 'CAPTUR', añoFabricacion: 2013, precio: 114500000, consumoCombustible: 12.00, color: 'Blanco', capacidadPasajeros: 5, tipoTransmision: 'Transmisión manual de 6 velocidades o una transmisión automática de 7 velocidades con doble embrague y palancas en el volante', potenciaMotor:  114, sistemaSeguridad: 'Airbags frontales y laterales, anclajes ISOFIX en las plazas traseras, cámara y sensores de estacionamiento traseros, limitador y regulador de velocidad, sensor crepuscular y de lluvia, LEDs delanteros diurnos (DRL), luces de esquina,etc.'},
  {marca: 'Mercedes-Benz', modelo: 'Clase G 580', añoFabricacion: 1979, precio: 4223829481, consumoCombustible:28.9 , color: 'Azul', capacidadPasajeros: 5, tipoTransmision: 'Transmisión de dos velocidades', potenciaMotor: 587, sistemaSeguridad: 'Airbags,Alerta de cambio involuntario de carril,Alerta para peatones mediante sonido,Amortiguación adaptativa,Antibloqueo de frenos (ABS),Aparcamiento asistido,Asistente activo de dirección,Asistente de frenado activo,Asistente para luz de carretera Plus,Mandos multifunción en volante,etc.'},
  {marca: 'Peugeot', modelo: 'SUV PEUGEOT 5008', añoFabricacion: 2016, precio: 179990000, consumoCombustible: 6.8, color: 'Negro', capacidadPasajeros: 7, tipoTransmision: 'AUTOMÁTICA 6 VELOCIDADES TIPO QUICKSHIFT', potenciaMotor: 165, sistemaSeguridad: 'AIRBAGS,ABS (Antibloqueo de llantas) + REF (repartidor electrónico de frenado),AFU (Asistencia al frenado de emergencia),ESP (Programa Electrónico de Estabilidad),ASR (Ayuda antipatinaje),TSA (Asistencia a la Estabilidad del remolque)'},
  {marca: 'BMW', modelo: 'X5', añoFabricacion: 1999, precio: 349900000, consumoCombustible: 21, color: 'Dravitgrau metalizado', capacidadPasajeros: 5, tipoTransmision: 'Automática deportiva de 8 velocidades', potenciaMotor: 280, sistemaSeguridad: 'Airbags,ABS,control de estabilidad,cámara de marcha atrás y monitoreo de presión de neumáticos,faros LED automáticos con luces altas automáticas,limpiaparabrisas con sensor de lluvia,un interior con oscurecimiento automático,sensores de estacionamiento delanteros y traseros,detección activa de puntos ciegos,etc.'},
  {marca: 'Audi', modelo: 'Q3 Sportback 35 TFSI Ambition Plus 2023', añoFabricacion: 2018, precio: 195400000, consumoCombustible: 	11.80, color: 'Plata', capacidadPasajeros: 5, tipoTransmision: 'S Tronic de 6 velocidades', potenciaMotor: 150, sistemaSeguridad: 'Airbags, sistema de frenos (ABS) con (EBD) y asistencia de frenado, control de estabilidad (ESC) y control de tracción (ASR), Sistema antirobo, etc.'},
  {marca: 'Fiat', modelo: 'Mobi like 2024', añoFabricacion: 2016, precio: 54990000, consumoCombustible: 16.25, color: 'Blanco', capacidadPasajeros: 5, tipoTransmision: 'Manual 5 velocidades y marcha', potenciaMotor: 69, sistemaSeguridad: 'Sistema de Frenos Antibloqueo (ABS), Sistema Emergency Stop Signaling (ESS) y sistema de sujeción de sillas para niños (ISOFIX)'},
  {marca: 'Maruti', modelo: 'Alto K10', añoFabricacion: 1979, precio: 41000000, consumoCombustible: 21.7, color: 'Rojo', capacidadPasajeros: 5, tipoTransmision: 'Manual', potenciaMotor: 67, sistemaSeguridad: 'Puertas,inmovilizador,cinturones de seguridad,tercer stop,airbags'},
  {marca: 'Mazda', modelo: 'CX-50', añoFabricacion: 2022, precio: 173000000, consumoCombustible: 10, color: 'Rojo', capacidadPasajeros: 5, tipoTransmision: 'SKYACTIV-DRIVE, AT 6 vel. Activematic', potenciaMotor: 188, sistemaSeguridad: 'Sistema activo de iluminación frontal (AFS),Control automático de luces altas (HBC)Asistencia de permanencia en carril (LAS)+ Prevención de salida de la vía (ELK),Asistencia inteligente de frenado delantero (SBS),Asistencia de frenado trasero (SBS)'},
  {marca: 'Suzuki', modelo: 'JIMNY 5', añoFabricacion: 1970, precio: 135990000, consumoCombustible:  15.4, color: 'Verde', capacidadPasajeros: 4, tipoTransmision: 'All-Grip Pro(4x4 + Bajo)', potenciaMotor: 100, sistemaSeguridad: 'Airbags,Cinturones de seguridad,Anclaje Isofix para asiento de niños,Sistema de liberación de pedales de freno y embrague,Barras de protección laterales,ABS,ESP,Inmovilizador,Tercer stop,etc.'},
  {marca: 'Toyota', modelo: 'Hilux', añoFabricacion: 1968, precio: 29193000, consumoCombustible: 12, color: 'Gris', capacidadPasajeros: 5, tipoTransmision: 'Manual de 6 velocidades', potenciaMotor: 150, sistemaSeguridad: 'Airbags,ABS,Asistente de Frenado de Emergencia (BA) y Luces de Frenado de Emergencia (EBS),Control de Estabilidad (VSC),Control de Balanceo de Tráiler (TSC) y Control de Tracción (TRC),Control de Tracción Activo (A-TRC),Asistente de Arranque en Pendientes (HAC),Control de velocidad crucero,Bloqueo de diferencial trasero,Faros antiniebla,Cinturones de seguridad,etc.'},
  {marca: 'Volkswagen', modelo: 'Delivery 11.180', añoFabricacion: 2024, precio: 212990000, consumoCombustible: 32, color: 'Blanco', capacidadPasajeros: 3, tipoTransmision: 'Mécanica ZF 6 Vel', potenciaMotor: 175, sistemaSeguridad: 'No se especifica'},
  {marca: 'Jeep', modelo: 'WRANGLER TURBO', añoFabricacion: 1987, precio: 288000000, consumoCombustible: 11.7, color: 'Rojo', capacidadPasajeros: 4, tipoTransmision: '850RE Automática 8 velocidades', potenciaMotor: 270, sistemaSeguridad: 'Airbags,Barras en las puertas contra impactos laterales,Cinturones de seguridad,Sistema LATCH (anclaje asientos de niños),ABS (Sistema de Frenos Antibloqueo),EBD (Distribución Electrónica de Frenado),ESC (Control Electrónico de Estabilidad),BAS (Asistente de frenado),HSA (Asistente de Arranque en Pendientes),HDC (Asistente de Descenso en Pendientes),TC (Control de Tracción),etc.'},
  {marca: 'Toyota', modelo: 'SW4 Diamond 2024', añoFabricacion: 2018, precio: 70401000, consumoCombustible: 12, color: 'Blanco', capacidadPasajeros: 7, tipoTransmision: 'Automática de 6 velocidades (6 Súper ECT) y Automática de 6 velocidades (6 Súper ECT) y levas al volante', potenciaMotor: 204, sistemaSeguridad: 'Control de velocidad crucero adaptativo (ACC),Sistema de pre-colisión frontal (PCS),Sistema de alerta de cambio de carril(LDA),Alerta de punto ciego (BSM),Alerta de tráfico trasero (RCTA),Airbags,ABS con Distribución electrónica de la fuerza de frenado (EBD), Asistente de frenado de emergencia(BA) y Luces de frenado de emergencia (EBS),Control de estabilidad (VSC),etc.'},
  {marca: 'Honda', modelo: 'HR-V', añoFabricacion: 1999, precio: 129990000, consumoCombustible:  5.2, color: 'Verde', capacidadPasajeros: 5, tipoTransmision: 'CVT CON STEP-SHIFT Y OPCIÓN MODO SPORT', potenciaMotor: 119, sistemaSeguridad: 'airbags frontales, ABS, recordatorio del cinturón de seguridad frontal e ISOFIX de serie.'},
  {marca: 'Chevrolet', modelo: 'Captiva XL', añoFabricacion: 2006, precio: 129990000, consumoCombustible: 7.6, color: 'Gris', capacidadPasajeros: 7, tipoTransmision: 'Automática CVT (shift-tronic)', potenciaMotor: 148, sistemaSeguridad: 'Seguro eléctrico para la columna de dirección,Columna de dirección colapsable,Encendido de luces automático,Cinturones de seguridad de 3 puntos para ocupantes,delanteros, segunda y tercera fila,Anclajes de seguridad para asientos de bebés ISOFIX,Sistema de frenos ABS y EBD,Sistema de control electrónico de estabilidad,etc.'},
  {marca: 'Chevrolet', modelo: 'Tahoe Z71', añoFabricacion:  1995, precio: 362990000, consumoCombustible: 7.18, color: 'Plata', capacidadPasajeros: 7, tipoTransmision: 'Automática de 10 velocidades', potenciaMotor: 355, sistemaSeguridad: 'Tecnología OnStar,Airbags,Frenos de disco de 17 en 4 ruedas con ABS + EBD,Asistente de frenado hidráulico (HBA),Control de estabilidad (ESC),Control de tracción (TCS),Asistente de arranque en pendiente (HSA),Control de descenso (HDC),Asistente indicador de distancia,Alerta de colisión frontal,Frenado automático de baja velocidad,etc.'},
  {marca: 'Honda', modelo: 'Prologue', añoFabricacion: 2024, precio: 199391232, consumoCombustible: 17.8, color: 'Negro', capacidadPasajeros: 5, tipoTransmision: 'transmisión eléctrica avanzada', potenciaMotor: 212, sistemaSeguridad: 'Frenado de Emergencia Automático,standard feature Frenado de Emergencia Automático,Sistema de mitigación de salida de carril,standard feature Sistema de mitigación de salida de carril,Dirección asistida en zona ciega,standard feature Dirección asistida en zona ciega,Cámara de visión trasera multiángulo standard feature, Cámara de visión trasera multiángulo,etc.'},
  {marca: 'Toyota', modelo: 'Hiace Wagon 2024', añoFabricacion: 1967, precio: 190000000, consumoCombustible: 8.5, color: 'Negro', capacidadPasajeros: 10, tipoTransmision: 'Automática de 6 velocidades', potenciaMotor: 163, sistemaSeguridad: 'Control de velocidad crucero adaptativo (ACC),Sistema de pre-colisión frontal (PCS),Sistema de alerta de cambio de carril (LDA),Sistema de luces altas automáticas (AHB),Alerta de punto ciego (BSM),Alerta de tráfico trasero (RCTA),Alarma antirrobo e inmovilizador de motor,ABS con distribución electrónica de la fuerza de frenado (EBD),Asistente de frenado de emergencia (BA),etc.'},
  {marca: 'Ford', modelo: 'Nueva Bronco', añoFabricacion: 2021, precio: 314990000, consumoCombustible: 14.94, color: 'Azul', capacidadPasajeros: 5, tipoTransmision: 'automática 10R80 de 10 velocidades con función skip shift y modo secuencial.', potenciaMotor: 237, sistemaSeguridad: 'Asistente de pre-colisión con frenado automático de emergencia y detección de peatones,Sistema de permanencia en el carril,Encendido de luces bajas y altas automático,Sistema de frenado post-colisión,Reconocimiento de señales de tránsito,Sensores de parqueo delanteros y traseros,Control de velocidad crucero adaptativo con Stop & Go y sistema de centrado de carril,etc.'},
  {marca: 'Nissan', modelo: 'Sentra 2025', añoFabricacion: 1982, precio: 118990000, consumoCombustible: 11.00, color: 'Azul', capacidadPasajeros: 5, tipoTransmision: 'Continuamente Variable (CVT)', potenciaMotor: 145, sistemaSeguridad: 'Doble airbag frontal,Doble airbag lateral,Doble airbag tipo cortina,Sistema de anclaje para silla de bebé en asiento trasero ISOFIX,Alerta de puerta trasera,Control dinámico del vehículo (VDC),Control de ascenso en pendientes (HSA),Advertencia de punto ciego (BSW),Alerta de tráfico cruzado (RCTA),Asistente de frenado de Emergencia,Inteligente con detección de peatones (IEB),etc.'},
  {marca: 'Jeep', modelo: 'GRAND CHEROKEE L', añoFabricacion: 1992, precio: 280000000, consumoCombustible: 7.94, color: 'Gris', capacidadPasajeros: 7, tipoTransmision: ' Automática 8 Velocidades', potenciaMotor: 293, sistemaSeguridad: 'Airbags,Cinturones de seguridad,ABS (Sistema de Frenos Antibloqueo),EBD (Distribución Electrónica de Frenado),ESC (Control Electrónico de Estabilidad),TC (Control de Tracción),HSA (Asistente de Arranque en Pendiente),BAS (Asistente de Frenado Control de velocidad,Sensores delanteros y traseros,Cámara de visión trasera,Cámara de visión trasera interior,etc.'},
  {marca: 'Kia', modelo: 'Soluto Emotion MT', añoFabricacion: 2017, precio: 65990000, consumoCombustible: 8.5, color: 'Negro', capacidadPasajeros: 5, tipoTransmision: 'Mecánica de 5 Velocidades', potenciaMotor: 94, sistemaSeguridad: 'ABS (Sistema Antibloqueo de Freno),Airbags,Cámara de reversa,Apoyacabezas delanteros ajustables en altura,Cinturones de seguridad delanteros y traseros retráctiles e inerciales de tres puntos,Barras protectoras de impacto en las cuatro puertas,etc.'},
  {marca: 'Chevrolet', modelo: 'Montana', añoFabricacion: 2003, precio: 80290000, consumoCombustible: 6.2, color: 'Verde', capacidadPasajeros: 5, tipoTransmision: 'MT 5 velocidades', potenciaMotor: 130, sistemaSeguridad: 'Airbags,ISOFIX y TOP TETHER,Luces diurnas LED,Control de crucero,Limitador de velocidad,Control de tracción,Seguridad,Aviso de cinturón de seguridad para pasajeros,Sistema de frenos con ABS y sistema distribución de freno (EBD),Control electrónico de estabilidad,etc.'},
  {marca: 'Renault', modelo: 'Duster', añoFabricacion: 2009, precio: 81400000, consumoCombustible: 8.9, color: 'Rojo', capacidadPasajeros: 5, tipoTransmision: 'Manual de 5 velocidades + reversa', potenciaMotor: 114, sistemaSeguridad: 'ABS+ REF (Sistema antibloqueo de frenos, Repartidor electrónico de frenado),Control de estabilidad y tracción (ESP / TCS),Asistente de arranque en pendiente (HSA),Control de Descenso (HDC),LV / RV Limitador Velocidad y Cruise Control'},
  {marca: 'Toyota', modelo: 'Hiace Commuter 2024', añoFabricacion: 1982, precio: 55698000, consumoCombustible: 6.40, color: 'Blanco', capacidadPasajeros: 12, tipoTransmision: 'Automática de 6 velocidades', potenciaMotor: 163, sistemaSeguridad: 'Control de velocidad crucero adaptativo (ACC),Sistema de pre-colisión frontal (PCS),Sistema de alerta de cambio de carril (LDA),Sistema de luces altas automáticas (AHB),Alerta de punto ciego (BSM),Alerta de tráfico trasero (RCTA),Alarma antirrobo e inmovilizador de motor,ABS con distribución electrónica de la fuerza de frenado (EBD),Asistente de frenado de emergencia (BA),etc.'},
  {marca: 'Lexus', modelo: 'LS', añoFabricacion: 1989, precio: 552039763, consumoCombustible: 10.8, color: 'Plata', capacidadPasajeros: 5, tipoTransmision: 'Tracción Rwd', potenciaMotor: 264, sistemaSeguridad: 'Accionamiento Automático de Luces de Carretera (AHB),Active brake lights,Anti-lock Braking System (ABS),Asistencia de Trayectoria en el Carril (LKA),Control de Crucero Adaptativo (desde 0 km/h),Control Electrónico de Estabilidad (VSC),Detección de ciclistas (día),Detección de peatones (día y noche),Dirección Asistida Eléctrica (EPS),Electronic Brake-force Distribution (EBD),etc.'},
  {marca: 'Kia', modelo: 'EV9', añoFabricacion: 2023, precio: 389990000, consumoCombustible: 22.8, color: 'Blanco', capacidadPasajeros: 6, tipoTransmision: 'Cambio electrónico tipo columna SBW con botón de arranque integrado', potenciaMotor: 378, sistemaSeguridad: 'ABS (Sistema antibloqueo de freno),ESC (Sistema de control electr쎣nico de estabilidad),HAC (Asistente de arranque en pendiente),TSA (Sistema de control estabilizador de remolque),TPMS (Sistema de monitoreo de presi쎣n de llantas),ROA (Alerta de ocupante trasero con sensor),BCA (Prevencion de Colisi쎣n en punto ciego),FCA (Asistente para evitar colisiones frontales en cruces e intersecciones),LFA (Asistente seguimiento de carril),Airbags delanteros para piloto y copiloto'},
  {marca: 'Lexus', modelo: 'RZ', añoFabricacion: 2021, precio: 268597521, consumoCombustible: 18, color: 'Negro', capacidadPasajeros: 5, tipoTransmision: 'Tracción FWD', potenciaMotor: 160 , sistemaSeguridad: 'Sistema de precolisión (PCS),Reconocimiento de Señales Tráfico (RSA),Luces traseras de emergencia con parpadeo automático (FHL),Anulación de Airbag pasajero delantero,Sistema de retención con sujeción ISOFIX,Airbags,Seguro de puertas,Cinturones de seguridad con aviso acústico y visual'},
  {marca: 'Chevrolet', modelo: 'Equinox', añoFabricacion: 2004, precio: 240990000, consumoCombustible: 10.40, color: 'Rojo', capacidadPasajeros: 5, tipoTransmision: 'automática de 6 velocidades con función tip up / tip down', potenciaMotor: 170, sistemaSeguridad: '5 CINTURONES DE SEGURIDAD RETRÁCTILES,6 AIRBAGS,LUCES ANTI NIEBLA,SENSORES DE ESTACIONAMIENTO,FRENOS DURALIFE ABS + EBD + BA,CONTROL ELECTRÓNICO DE ESTABILIDAD STABILITRAK,CÁMARA DE VISIÓN TRASERA'},
  {marca: 'Hyundai', modelo: 'Kona Híbrida', añoFabricacion: 2017, precio: 139990000, consumoCombustible: 5.20, color: 'Gris', capacidadPasajeros: 5, tipoTransmision: 'Automática de 6 velocidades + reversa', potenciaMotor: 139, sistemaSeguridad: 'ABS (Sistema Antibloqueo de Frenos),EBD (Distribución Electrónica de Frenado),ESC (Control Electrónico de Estabilidad ),HAC (Asistente de Ascenso en Pendientes),MCB (Multicollision brake),MDPS (Dirección Electroasistida),TPMS (Monitoreo de Presión de LLantas),Cámara de reversa con guía dinámica,Sensores de parqueo,DMS (Selector de modo de manejo)'},
  {marca: 'Ford', modelo: 'Mustang', añoFabricacion: 1964, precio:  259990000, consumoCombustible: 10.5, color: 'Plata', capacidadPasajeros: 4, tipoTransmision: 'automática de 10 velocidades con capacidad SelectShift', potenciaMotor: 486, sistemaSeguridad: 'Espejo retrovisor sin marco con anti-deslumbramiento,Anclajes inferiores y anclajes de sujeción para niños ISOFIX,Kit de sellador e inflador de neumáticos,Sistema de Seguridad Personal™ para el conductor y pasajero delantero: Pretensores de cinturones de seguridad,Sistema antirrobo activo,Consola central con bloqueo electrónico,Kit de bloqueo de ruedas,etc.'},
  {marca: 'Volkswagen', modelo: 'Jetta Turbo', añoFabricacion: 2018, precio: 112990000, consumoCombustible: 12.20, color: 'Negro', capacidadPasajeros: 5, tipoTransmision: 'Automática Tiptronic 6 velocidades', potenciaMotor: 150, sistemaSeguridad: 'Airbag,Sistema de control electrónico de estabilidad (ESC),Sistema antibloqueo de ruedas (ABS),Sistema de control de tracción (ASR),Sistema de control electrónico de diferencial (EDL),Asistente de arranque en pendiente,Barras estabilizadoras,Activación de las luces direccionales en caso de emergencia,Sistema de asistencia hidráulica de frenado (HBA),etc.'},
  {marca: 'Volkswagen', modelo: 'Jetta Turbo 2', añoFabricacion: 2018, precio: 112990000, consumoCombustible: 12.20, color: 'Negro', capacidadPasajeros: 5, tipoTransmision: 'Automática Tiptronic 6 velocidades', potenciaMotor: 150, sistemaSeguridad: 'Airbag,Sistema de control electrónico de estabilidad (ESC),Sistema antibloqueo de ruedas (ABS),Sistema de control de tracción (ASR),Sistema de control electrónico de diferencial (EDL),Asistente de arranque en pendiente,Barras estabilizadoras,Activación de las luces direccionales en caso de emergencia,Sistema de asistencia hidráulica de frenado (HBA),etc.'}
 
]);

//Búsquedas
db.cars.find({color:{$eq:'Blanco'}}) //Busca los carros que sólo tengan color Blanco

//db.cars.find({añoFabricacion:{$gt:2000}}) //Busca los carros cuyo año de fabricación sea mayor a los 2000

//db.cars.find({precio:{$gte:200000000}}) //Busca los carros cuyo precio sea mayor o igual a 200.000.000

//db.cars.find({capacidadPasajeros:{$lt:5}}) //Busca los carros que tengan una capacidad de pasajeros menor a 5

//db.cars.find({potenciaMotor:{$lte:100}}) //Busca los carros que tengan una potencia de motor menor o igual que 100

//db.cars.find({marca:{$ne:"Toyota"}}) //Busca los carros que sean diferente de la marca Toyota

//db.cars.find({marca:{$in:["Honda","Toyota","Nissan"]}}) //Busca los carros que tengan como marca a HONDA,TOYOTA O  NISSAN

//db.cars.find({color:{$nin:["Blanco","Negro","Gris"]}}) //Busca los carros que no sean de color Blanco, Negro o Gris

//db.cars.find({marca:"Ford", añoFabricacion:{$gte:2020}}) //Busca los carros que sean de la marca Ford y su año de fabricación sea mayor o igual al 2020

//db.cars.deleteOne({modelo:"Jetta Turbo 2"}) //Elimina el carro haciendo uso del modelo
