//Base de datos de los hoteles más reconocidos del mundo

db.hotel.insertMany([
  
  {nombreHotel: 'Capella Bangkok', ubicacion: 'Four Seasons Private Residences Bangkok, 300, 2 Charoen Krung Road, Yan Nawa, Sathon, Bangkok 10120, Tailandia', clasificacion: 5, descripcion: 'Con vistas panorámicas al majestuoso río Chao Phraya, Capella Bangkok, uno de los hoteles de cinco estrellas de lujo de Bangkok, Tailandia, es una puerta de entrada a la eterna belleza de la naturaleza y al oasis urbano de la ciudad.', capacidadPersonas: 3, areaHotel: 11000, tarifaPromedio: 1500, numeroPisos: 11, tamañoHabitaciones: "61 m²", ingresosMensuales: 4500000},
  {nombreHotel: 'Passalacqua', ubicacion: 'Via Besana, 59, 22010 Moltrasio CO, Italia', clasificacion: 5, descripcion: 'Villa histórica convertida en hotel de lujo con vistas al Lago de Como, jardines exuberantes y servicio personalizado.', capacidadPersonas: 2, areaHotel: 8000, tarifaPromedio: 2000, numeroPisos: 3, tamañoHabitaciones: "80 m²", ingresosMensuales: 3000000},
  {nombreHotel: 'Rosewood Hong Kong', ubicacion: 'Victoria Dockside, 18 Salisbury Road, Tsim Sha Tsui, Hong Kong', clasificacion: 5, descripcion: 'Rascacielos de lujocon vistas al puerto de Victoria, spa de última generación y múltiples opciones gastronómicas.', capacidadPersonas: 4, areaHotel: 43000, tarifaPromedio: 1800, numeroPisos: 65, tamañoHabitaciones: '55 m²', ingresosMensuales: 9000000},
  {nombreHotel: 'Cheval Blanc', ubicacion: '8 Quai du Point du Jour, 92100 Boulogne-Billancourt, Francia', clasificacion: 5, descripcion: 'Hotel boutique de ultra lujo en París con diseño contemporáneo, spa Dior y vistas al Sena.', capacidadPersonas: 3, areaHotel: 15000, tarifaPromedio: 2500, numeroPisos: 7, tamañoHabitaciones: '70 m²', ingresosMensuales: 6000000},
  {nombreHotel: 'The Upper House', ubicacion: 'Pacific Place, 88 Queensway, Admiralty, Hong Kong', clasificacion: 5, descripcion: 'Hotel de diseño contemporáneo con amplias habitaciones, vistas panorámicas de la ciudad y servicio personalizado.', capacidadPersonas: 3, areaHotel: 20000, tarifaPromedio: 1200, numeroPisos: 49, tamañoHabitaciones: '68 m²', ingresosMensuales: 5500000},
  {nombreHotel: 'Raffles Singapore', ubicacion: '1 Beach Road, 189673, Singapur', clasificacion: 5, descripcion: 'Hotel histórico icónico de Singapur, recientemente renovado, famoso por su arquitectura colonial y el cóctel Singapore Sling.', capacidadPersonas: 3, areaHotel: 40000, tarifaPromedio: 1300, numeroPisos: 3, tamañoHabitaciones: '60 m²', ingresosMensuales: 7000000},
  {nombreHotel: 'Aman Tokyo', ubicacion: 'The Otemachi Tower, 1-5-6 Otemachi, Chidoya-ku, Tokyo 100-0004', clasificacion: 5, descripcion: 'Hotel de lujo minimalista en lo alto de un rascacielos con spa, vistas panorámicas de Tokio y diseño zen.', capacidadPersonas: 3, areaHotel: 25000, tarifaPromedio: 1600, numeroPisos: 6, tamañoHabitaciones: '71 m²', ingresosMensuales: 6500000},
  {nombreHotel: 'Soneva Fushi', ubicacion: 'Kunfunadhoo Island, Baa Atoll, Maldivas', clasificacion: 5, descripcion: 'Resort de lujo ecológico en una isla privada con villas en la playa, experiencias únicas y compromiso con la sostenibilidad.', capacidadPersonas: 6, areaHotel: 100000, tarifaPromedio: 3000, numeroPisos: 1, tamañoHabitaciones: '250 m²', ingresosMensuales: 8000000},
  {nombreHotel: 'Atlantis The Royal', ubicacion: 'Crescent Road, Palm Jumeirah, Dubai, Emiratos Árabes Unidos', clasificacion: 5, descripcion: 'Resort ultra lujoso en Dubai con arquitectura futurista, fuentes espectaculares y experiencias gastronómicas de clase mundial.', capacidadPersonas: 4, areaHotel: 170000, tarifaPromedio: 2000, numeroPisos: 43, tamañoHabitaciones: '75 m²', ingresosMensuales: 15000000},
  {nombreHotel: 'Nihi Sumba', ubicacion: 'Hoba Wawi, Wanokaka, Sumba Barat, East Nusa Tenggara, Indonesia', clasificacion: 5, descripcion: 'Resort exclusivo en una isla remota de Indonesia, conocido por sus playas vírgenes y experiencias de aventura de lujo.', capacidadPersonas: 4, areaHotel: 200000, tarifaPromedio: 1800, numeroPisos: 1, tamañoHabitaciones: '200 m²', ingresosMensuales: 4000000},
  {nombreHotel: 'Claridge’s', ubicacion: 'Brook Street, Myfair, London W1K 4HR, Reino Unido', clasificacion: 5, descripcion: 'Hotel icónico en el corazón de Mayfair, Londres, conocido por su elegancia atemporal y servicio excepcional.', capacidadPersonas: 3, areaHotel: 30000, tarifaPromedio: 1700, numeroPisos: 7, tamañoHabitaciones: '50 m²', ingresosMensuales: 8500000},
  {nombreHotel: 'Mandarin Oriental Bangkok', ubicacion: '48 Oriental Avenue, Bangkok 10500, Tailandia', clasificacion: 5, descripcion: 'Hotel legendario a orillas del río Chao Phraya, que combina el lujo tailandés con la hospitalidad contemporánea.', capacidadPersonas: 3, areaHotel: 55000, tarifaPromedio: 1400, numeroPisos: 16, tamañoHabitaciones: '63 m²', ingresosMensuales: 7500000},
  {nombreHotel: 'Raffles London at The OWO', ubicacion: 'Whitehall, London SW1A 2EU, Reino Unido', clasificacion: 5, descripcion: 'Nuevo hotel de lujo en el histórico Old War Office, que ofrece una experiencia única en el corazón de Londres.', capacidadPersonas: 3, areaHotel: 50000, tarifaPromedio: 2200, numeroPisos: 9, tamañoHabitaciones: '70 m²', ingresosMensuales: 9000000},
  {nombreHotel: 'Four Seasons Bangkok at Chao Phraya River', ubicacion: '300/1 Charoen Krung Road, Sathorn, Bangkok 10120, Tailandia', clasificacion: 5, descripcion: 'Moderno oasis urbano a orillas del río que ofrece una experiencia de lujo contemporáneo en Bangkok.', capacidadPersonas: 3, areaHotel: 60000, tarifaPromedio: 1300, numeroPisos: 9, tamañoHabitaciones: '60 m²', ingresosMensuales: 6800000},
  {nombreHotel: 'Hôtel de Crillon', ubicacion: '10 Place de la Concorde, 75008 París, Francia', clasificacion: 5, descripcion: 'Palacio del siglo XVIII convertido en hotel de lujo que ofrece una experiencia parisina refinada y elegante.', capacidadPersonas: 3, areaHotel: 25000, tarifaPromedio: 2100, numeroPisos: 6, tamañoHabitaciones: '58 m²', ingresosMensuales: 7200000},
  {nombreHotel: 'Chablé Yucatán', ubicacion: 'Tablaje 642, 97816 Chocholá, Yucatán, México', clasificacion: 5, descripcion: 'Resort de lujo en la selva yucateca, que combina la cultura maya con el bienestar contemporáneo.', capacidadPersonas: 2, areaHotel: 300000, tarifaPromedio: 1600, numeroPisos: 1, tamañoHabitaciones: '120 m²', ingresosMensuales: 3500000},
  {nombreHotel: 'Hotel du Cap-Eden-Roc', ubicacion: 'Boulevard J.F. Kennedy, 06601 Antibes, Francia', clasificacion: 5, descripcion: 'Icónico hotel de la Riviera Francesa, conocido por su glamour atemporal y vistas al Mediterráneo.', capacidadPersonas: 3, areaHotel: 90000, tarifaPromedio: 2800, numeroPisos: 5, tamañoHabitaciones: '65 m²', ingresosMensuales: 10000000},
  {nombreHotel: 'Maroma', ubicacion: 'Carretera Cancún-Tulum Km 51, 77710 Playa del Carmen, Q.R., México', clasificacion: 5, descripcion: 'Resort de playa de lujo en la Riviera Maya, que ofrece una experiencia íntima en un entorno tropical.', capacidadPersonas: 3, areaHotel: 80000, tarifaPromedio: 1900, numeroPisos: 3, tamañoHabitaciones: '75 m²', ingresosMensuales: 5500000},
  {nombreHotel: 'Four Seasons Firenze', ubicacion: 'Borgo Pinti, 99, 50121 Firenze FI, Italia', clasificacion: 5, descripcion: 'Palacio renacentista convertido en hotel de lujo, que ofrece una experiencia única en el corazón de Florencia.', capacidadPersonas: 3, areaHotel: 45000, tarifaPromedio: 1800, numeroPisos: 4, tamañoHabitaciones: '55 m²', ingresosMensuales: 6000000},
  {nombreHotel: 'Borgo Santandrea', ubicacion: 'Via Giovanni Augustariccio, 33, 84011 Amalfi SA, Italia', clasificacion: 5, descripcion: 'Hotel boutique de lujo en la costa de Amalfi, que combina el diseño moderno con las vistas al Mar Mediterráneo.', capacidadPersonas: 2, areaHotel: 20000, tarifaPromedio: 2200, numeroPisos: 6, tamañoHabitaciones: '45 m²', ingresosMensuales: 4500000},
  {nombreHotel: 'Desa Potato Head', ubicacion: 'Jl. Petitenget No.51B, Seminyak, Kec. Kuta Utara, Bali, Indonesia', clasificacion: 5, descripcion: 'Resort creativo y sostenible en Bali, que ofrece una experiencia única de arte, música y gastronnomía.', capacidadPersonas: 3, areaHotel: 70000, tarifaPromedio: 1100, numeroPisos: 5, tamañoHabitaciones: '50 m²', ingresosMensuales: 4000000},
  {nombreHotel: 'Bulgari Tokyo', ubicacion: '2-2-1 Yaesu, Chuo City, Tokyo 104-0028', clasificacion: 5, descripcion: 'Hotel de lujo contemporáneo en el corazón de Tokio, que refleja la elegancia de la marca Bulgari.', capacidadPersonas: 3, areaHotel: 35000, tarifaPromedio: 2000, numeroPisos: 45, tamañoHabitaciones: '60 m²', ingresosMensuales: 8000000},
  {nombreHotel: 'The Lana', ubicacion: 'Marasi Drive, Business Bay, Dubai, Emiratos Árabes Unidos', clasificacion: 5, descripcion: 'Hotel de diseño vanguardista en Dubai, que ofrece vistas panorámicas y experiencias de lujo únicas.', capacidadPersonas: 3, areaHotel: 55000, tarifaPromedio: 1700, numeroPisos: 30, tamañoHabitaciones: '65 m²', ingresosMensuales: 7000000},
  {nombreHotel: 'Rosewood São Paulo', ubicacion: 'Rua Itapeva, 435-Bela Vista, Sao Paulo-SP, 01332-000, Brasil', clasificacion: 5, descripcion: 'Hotel de lujo en un rascacielos histórico de Sao Pulo, que combina el arte brasileño con la sofisticación contemporánea.', capacidadPersonas: 3, areaHotel: 40000, tarifaPromedio: 1400, numeroPisos: 22, tamañoHabitaciones: '58 m²', ingresosMensuales: 5800000},
  {nombreHotel: 'The Calile', ubicacion: '48 James St, Fortitude Valley QLD 4006, Australia', clasificacion: 5, descripcion: 'Hotel urbano de diseño en Brisbane, que ofrece una experiencia de lujo relajada con influencias mediterráneas.', capacidadPersonas: 2, areaHotel: 25000, tarifaPromedio: 450, numeroPisos: 7, tamañoHabitaciones: '45 m²', ingresosMensuales: 3200000},
  {nombreHotel: 'The Siam', ubicacion: '3/2 Khao Rd, Wachira Phayaban, Dusit District, Bangkok 10300, Tailandia', clasificacion: 5, descripcion: 'Hotel boutique de lujo a orillas del río Bangkok, que ofrece un oasis urbano con diseño art deco.', capacidadPersonas: 3, areaHotel: 30000, tarifaPromedio: 1300, numeroPisos: 3, tamañoHabitaciones: '80 m²', ingresosMensuales: 4500000},
  {nombreHotel: 'Park Hyatt Kyoto', ubicacion: '360 Kodaiji Maekawa-cho, Higashiyama-ku, Kyoto 605-0825', clasificacion: 5, descripcion: 'Hotel de lujo en el corazón histórico de Kioto, que fusiona la tradición japonesa con el confort moderno,', capacidadPersonas: 3, areaHotel: 28000, tarifaPromedio: 1600, numeroPisos: 5, tamañoHabitaciones: '55 m²', ingresosMensuales: 5500000},
  {nombreHotel: 'Mount Nelson', ubicacion: '76 Orange St, Gardens, Cape Town, 8001, Sudáfrica', clasificacion: 5, descripcion: 'Hotel histórico de lujo en Ciudad del Cabo, conocido por su elegancia colonial y jardines exuberantes.', capacidadPersonas: 3, areaHotel: 50000, tarifaPromedio: 1100, numeroPisos: 4, tamañoHabitaciones: '50 m²', ingresosMensuales: 4800000},
  {nombreHotel: 'One&Only Mandarina', ubicacion: 'Carretera Federal 200 Km 87, 63729 El Monteón, Nayarit, México', clasificacion: 5, descripcion: 'Resort de lujo en la costa pacífica de México, que ofrece villas privadas y experiencias de aventura exclusivas.', capacidadPersonas: 4, areaHotel: 150000, tarifaPromedio: 2500, numeroPisos: 1, tamañoHabitaciones: '180 m²', ingresosMensuales: 7500000},
  {nombreHotel: 'The Carlyle', ubicacion: '35 E 76th St, New York, NY 10021, Estados Unidos', clasificacion: 5, descripcion: 'Hotel icónico del Upper East Side de Nueva York, conocido por su elegancia atemporal y su famoso bar de jazz.', capacidadPersonas: 3, areaHotel: 35000, tarifaPromedio: 1800, numeroPisos: 35, tamañoHabitaciones: '55 m²', ingresosMensuales: 8500000},
  {nombreHotel: 'La Mamounia', ubicacion: 'Avenue Bab Jdid, 40040 Marrakech, Marruecos', clasificacion: 5, descripcion: 'Palacio marroquí convertido en hotel de lujo, que ofrece una experiencia opulenta en el corazón de Marrakech.', capacidadPersonas: 3, areaHotel: 80000, tarifaPromedio: 1500, numeroPisos: 4, tamañoHabitaciones: '65 m²', ingresosMensuales: 6500000},
  {nombreHotel: 'Four Seasons Madrid', ubicacion: 'Calle de Sevilla, 3, 28014 Madrid, España', clasificacion: 5, descripcion: 'Hotel de lujo en el centro histórico de Madrid, que ocupa varios edificios históricos restaurados.', capacidadPersonas: 3, areaHotel: 45000, tarifaPromedio: 1400, numeroPisos: 7, tamañoHabitaciones: '60 m²', ingresosMensuales: 6000000},
  {nombreHotel: 'Capella Singapore', ubicacion: '1 The Knolls, Sentosa Island, Singapore 098297', clasificacion: 5, descripcion: 'Resort de lujo en la isla de Sentosa que combina el encanto colonial con el diseño contemporáneo.', capacidadPersonas: 3, areaHotel: 120000, tarifaPromedio: 1300, numeroPisos: 3, tamañoHabitaciones: '70 m²', ingresosMensuales: 5500000},
  {nombreHotel: 'Four Seasons at The Surf Club', ubicacion: '9011 Collins Ave, Surfside, FL 33154, Estados Unidos', clasificacion: 5, descripcion: 'Hotel histórico renovado en la costa de Miami, que ofrece lujo contemporáneo y vistas al océano.', capacidadPersonas: 3, areaHotel: 40000, tarifaPromedio: 2000, numeroPisos: 12, tamañoHabitaciones: '75 m²', ingresosMensuales: 7000000},
  {nombreHotel: 'Hotel Bel-Air', ubicacion: '701 Stone Canyon Rd, Los Angeles, CA 90077, Estados Unidos', clasificacion: 5, descripcion: 'Oasis de lujo en los Angeles, conocido por sus jardines exuberantes y su atmósfera íntima y exclusiva.', capacidadPersonas: 3, areaHotel: 50000, tarifaPromedio: 1700, numeroPisos: 2, tamañoHabitaciones: '85 m²', ingresosMensuales: 6800000},
  {nombreHotel: 'Eden Rock', ubicacion: 'Baie de Saint Jean, St Barthélemy 97133, Antillas Francesas', clasificacion: 5, descripcion: 'Hotel icónico en St. Barths, situado en un promontorio rocoso con vistas panorámicas al Caribe.', capacidadPersonas: 3, areaHotel: 25000, tarifaPromedio: 2800, numeroPisos: 3, tamañoHabitaciones: '70 m²', ingresosMensuales: 8000000},
  {nombreHotel: 'Aman New York', ubicacion: 'The Crown Building, 730 5th Ave, New York, NY 10019, Estados Unidos', clasificacion: 5, descripcion: 'Hotel de lujo ultramoderno en el corazón de Manhattan, que ocupa un edificio histórico renovado.', capacidadPersonas: 3, areaHotel: 30000, tarifaPromedio: 2500, numeroPisos: 26, tamañoHabitaciones: '75 m²', ingresosMensuales: 9500000},
  {nombreHotel: 'Royal Mansour', ubicacion: 'Rue Abou Abbas El Sebti, 40000 Marrakech, Marruesco', clasificacion: 5, descripcion: 'Hotel de lujo en Marrakech, diseñado como una medina tradicional con riads privados y artesanía marroquí.', capacidadPersonas: 4, areaHotel: 100000, tarifaPromedio: 2200, numeroPisos: 3, tamañoHabitaciones: '150 m²', ingresosMensuales: 7500000},
  {nombreHotel: 'Amangalla', ubicacion: '10 Church St, Galle 80000, Sri Lanka', clasificacion: 5, descripcion: 'Un hotel de lujo ubicado en un edificio histórico del siglo XVII dentro de las murallas del Fuerte Galle, patrimonio de la UNESCO, ofrece una experiencia única combinando el encanto colonial con comodidades modernas.', capacidadPersonas: 2, areaHotel: 10000, tarifaPromedio: 1200, numeroPisos: 3, tamañoHabitaciones: '80 m²', ingresosMensuales: 3500000},
  {nombreHotel: 'Le Bristol', ubicacion: '112 Rue du Faubourg Saint-Honoré, 75008 Paris, Francia', clasificacion: 5, descripcion: 'Palacio parisino convertido en hotel de lujo, famoso por su elegancia clásica y su servicio excepcional.', capacidadPersonas: 3, areaHotel: 25000, tarifaPromedio: 2300, numeroPisos: 7, tamañoHabitaciones: '60 m²', ingresosMensuales: 8500000},
  
]);

//Búsquedas

db.hotel.find({nombreHotel:{$eq:'Capella Bangkok'}}) //Busca el hotel igual al nombre especificado 

//db.hotel.find({clasificacion:{$gt:5}}) //Busca los hoteles cuya clasificación sea mayor a 5 estrellas

//db.hotel.find({tarifaPromedio:{$gte:1500}}) //Busca los hoteles cuya tarifa promedio sea mayor o igual a 1500 dolares

//db.hotel.find({areaHotel:{$lt:20000}}) //Busca los hoteles cuya area total sea menor a 20000 metros cuadrados

//db.hotel.find({capacidadPersonas:{$lte:2}}) //Busca los hoteles cuya capacidad de personas por habitación sea menor o igual a 2

//db.hotel.find({ubicacion:{$ne:'Whitehall, London SW1A 2EU, Reino Unido'}}) //Busca los hoteles cuta ubicacion sea diferente a la especificada

//db.hotel.find({ingresosMensuales:{$in:[5000000,6000000,7000000]}}) //Busca los hoteles cuyos ingresos mensuales se encuentren entre los 5000000,6000000 0 7000000 dolares

//db.hotel.find({numeroPisos:{$nin:[1,3,5]}}) //Busca los hoteles cuyo número de pisos no se encuentre entre 1,3 o 5

//db.hotel.find({tamañoHabitaciones:'50 m²'}) //Busca los hoteles cuyo tamaño de habitaciones sea de 50 metros cuadrados

//db.hotel.deleteOne({nombreHotel:{$eq:'Eden Rock'}}) //Busca el hotel cuyo nombre sea igual a Eden Rock y lo elimina