//Base de datos de materias del programa de Ingeniería de Sistemas de la Universidad Mariana

db.subjects.insertMany([
  
  {nombreMateria: 'Algoritmos Y Programación I', codigoMateria: 84003, descripcion: 'Introducción al mundo de la programación y el diseño de algoritmos, su objetivo es enseñar los conceptos básicos necesarios para resolver problemas computacionales de manera eficiente, utilizando un lenguaje de programación.', creditos: 3, horasTeoricas: 0, horasPracticas: 64, profesorResponsable: 'Fabian Parra', aulaAsignada: '604', prerrequisitos: 'Ninguno', promedioCalificaciones: 3.5},
  {nombreMateria: 'Introducción a la Ingeniería', codigoMateria: 84004, descripcion: 'Tiene como objetivo brindar a los estudiantes una comprensión general sobre la profesión de la ingeniería, sus diferentes disciplinas y el rol que desempeñan los ingenieros en la sociedad.', creditos: 1, horasTeoricas: 32, horasPracticas: 0, profesorResponsable: 'Sebastian Carrera', aulaAsignada: '601', prerrequisitos: 'Ninguno', promedioCalificaciones: 3.0},
  {nombreMateria: 'Pensamiento Filosófico', codigoMateria: 84006, descripcion: 'Introducir a los estudiantes en los fundamentos de la filosofía, explorando sus principales conceptos, corrientes, y preguntas fundamentales sobre la existencia, el conocimiento, la verdad, la moral y la realidad.', creditos: 2, horasTeoricas: 32, horasPracticas: 0, profesorResponsable: 'Magally Morales', aulaAsignada: '406', prerrequisitos: 'Ninguno', promedioCalificaciones: 3.0},
  {nombreMateria: 'Fundamento Matemático', codigoMateria: 84001, descripcion: 'Proporcionar las bases esenciales de las matemáticas que son necesarias para abordar estudios más avanzados en disciplinas como la ingeniería, la economía, la informática o las ciencias exactas.', creditos: 2, horasTeoricas: 0, horasPracticas: 32, profesorResponsable: 'Danny Michael Cardenas Martínez', aulaAsignada: '204', prerrequisitos: 'Ninguno', promedioCalificaciones: 3.5},
  {nombreMateria: 'Lectoescritura Investigativa', codigoMateria: 84005, descripcion: 'Diseñada para desarrollar habilidades de lectura crítica, análisis y producción de textos académicos y científicos.', creditos: 1, horasTeoricas: 32, horasPracticas: 0, profesorResponsable: 'Javier Poveda', aulaAsignada: '408', prerrequisitos: 'Ninguno', promedioCalificaciones: 3.0},
  {nombreMateria: 'Lógica Matemática', codigoMateria: 84002, descripcion: 'Estudia los principios fundamentales del razonamiento matemático, proporcionando las herramientas necesarias para construir y evaluar argumentos de forma rigurosa y precisa.', creditos: 2, horasTeoricas: 48, horasPracticas: 0, profesorResponsable: 'Leidy Marcela Gómez Melo', aulaAsignada: '604', prerrequisitos: 'Ninguno', promedioCalificaciones: 3.0},
  {nombreMateria: 'Epistemología Específica', codigoMateria: 84014, descripcion: 'Se enfoca en el estudio del conocimiento dentro de disciplinas o áreas específicas, como las ciencias naturales, las ciencias sociales, las matemáticas, el arte, la ética, entre otras.', creditos: 1, horasTeoricas: 32, horasPracticas: 0, profesorResponsable: 'Javier Poveda', aulaAsignada: '501', prerrequisitos: 'Ninguno', promedioCalificaciones: 3.0},
  {nombreMateria: 'Humanismo Cristiano', codigoMateria: 84015, descripcion: 'Es una corriente filosófica y teológica que busca integrar los valores y principios del humanismo con la visión cristiana del mundo.', creditos: 2, horasTeoricas: 32, horasPracticas: 0, profesorResponsable: 'Mayerli Deraso', aulaAsignada: '406', prerrequisitos: 'Ninguno', promedioCalificaciones: 3.0},
  {nombreMateria: 'Mecánica', codigoMateria: 84013, descripcion: 'Rama de la física que estudia el movimiento de los cuerpos y las fuerzas que los afectan.', creditos: 3, horasTeoricas: 0, horasPracticas: 48, profesorResponsable: 'Favio Nicolas Rosero Rodríguez', aulaAsignada: 'Laboratorio de Fisica', prerrequisitos: 'Ninguno', promedioCalificaciones: 3.0},
  {nombreMateria: 'Algoritmos Y Programación II', codigoMateria: 84012, descripcion: 'Profundiza en la comprensión de los principios fundamentales de la programación y el diseño de algoritmos, introduciendo estructuras de datos más avanzadas y técnicas de análisis de algoritmos.', creditos: 3, horasTeoricas: 0, horasPracticas: 64, profesorResponsable: 'Javier Mauricio López Moreno', aulaAsignada: '604', prerrequisitos: 'Algoritmos Y Programación I', promedioCalificaciones: 3.5},
  {nombreMateria: 'Cálculo Diferencial', codigoMateria: 84011, descripcion: 'Rama fundamental del cálculo que se centra en el estudio de las tasas de cambio y la pendiente de las funciones.', creditos: 2, horasTeoricas: 0, horasPracticas: 48, profesorResponsable: 'Leidy Marcela Gómez Melo', aulaAsignada: '405', prerrequisitos: 'Fundamento Matemático', promedioCalificaciones: 3.5},
  {nombreMateria: 'Álgebra Lineal', codigoMateria: 84010, descripcion: 'Rama de las matemáticas que se centra en el estudio de vectores, espacios vectoriales, y las transformaciones lineales.', creditos: 2, horasTeoricas: 0, horasPracticas: 32, profesorResponsable: 'Edinson Benavides', aulaAsignada: '604', prerrequisitos: 'Fundamento Matemático', promedioCalificaciones: 3.5},
  {nombreMateria: 'Cálculo Integral', codigoMateria: 84019, descripcion: 'Rama del cálculo que se centra en el estudio de la integración de funciones, que es el proceso inverso de la derivación.', creditos: 2, horasTeoricas: 0, horasPracticas: 48, profesorResponsable: 'Leidy Marcela Gómez Melo', aulaAsignada: '202', prerrequisitos: 'Cálculo Diferencial', promedioCalificaciones: 3.5},
  {nombreMateria: 'Métodos Numéricos', codigoMateria: 84020, descripcion: 'Técnicas matemáticas que permiten encontrar aproximaciones a soluciones de problemas matemáticos que no se pueden resolver de manera exacta.', creditos: 2, horasTeoricas: 0, horasPracticas: 32, profesorResponsable: 'Javier Mauricio López Moreno', aulaAsignada: '601', prerrequisitos: 'Ninguno', promedioCalificaciones: 3.5},
  {nombreMateria: 'Ética Profesional', codigoMateria: 84023, descripcion: 'Conjunto de principios y normas que guían el comportamiento y la práctica de los profesionales en el ejercicio de su actividad.', creditos: 2, horasTeoricas: 32, horasPracticas: 0, profesorResponsable: 'Luis Francisco Melo', aulaAsignada: '506', prerrequisitos: 'Ninguno', promedioCalificaciones: 3.0},
  {nombreMateria: 'Electricidad Y Magnetismo', codigoMateria: 84022, descripcion: 'Rama de la física que estudia las interacciones entre cargas eléctricas y los campos eléctricos y magnéticos que se generan a partir de ellas.', creditos: 2, horasTeoricas: 48, horasPracticas: 0, profesorResponsable: 'Favio Nicolas Rosero Rodríguez', aulaAsignada: 'Laboratorio de Fisica', prerrequisitos: 'Mecánica', promedioCalificaciones: 3.0},
  {nombreMateria: 'Matemáticas Discretas', codigoMateria: 84018, descripcion: 'Rama de las matemáticas que se ocupa de estructuras y objetos que son contables o discretos, en contraposición a los que son continuos.', creditos: 2, horasTeoricas: 32, horasPracticas: 0, profesorResponsable: 'Erick Ortiz', aulaAsignada: '310', prerrequisitos: 'Ninguno', promedioCalificaciones: 3.0},
  {nombreMateria: 'Algoritmos Y Programación III', codigoMateria: 84021, descripcion: 'Curso avanzado que profundiza en el diseño, análisis y implementación de algoritmos complejos y estructuras de datos.', creditos: 3, horasTeoricas: 0, horasPracticas: 64, profesorResponsable: 'Sebastian Carrera', aulaAsignada: '601', prerrequisitos: 'Algoritmos Y Programación II', promedioCalificaciones: 3.5},
  {nombreMateria: 'Ecuaciones Diferenciales', codigoMateria: 84026, descripcion: 'Rama de las matemáticas que se ocupa del estudio de ecuaciones que involucran funciones y sus derivadas.', creditos: 2, horasTeoricas: 0, horasPracticas: 48, profesorResponsable: 'Erick Ortiz', aulaAsignada: '407', prerrequisitos: 'Cálculo Integral', promedioCalificaciones: 3.5},
  {nombreMateria: 'Probabilidad Y Estadística Descriptiva', codigoMateria: 84030, descripcion: 'Rama de las matemáticas que se centra en el análisis, interpretación y presentación de datos, así como en la formulación y análisis de modelos probabilísticos.', creditos: 3, horasTeoricas: 0, horasPracticas: 48, profesorResponsable: 'Leidy Marcela Gómez Melo', aulaAsignada: '604', prerrequisitos: 'Ninguno', promedioCalificaciones: 3.5},
  {nombreMateria: 'Interacción Hombre Máquina', codigoMateria: 84029, descripcion: 'Campo de estudio que se centra en el diseño y la evaluación de sistemas interactivos que facilitan la comunicación y el intercambio de información entre las personas y las máquinas.', creditos: 3, horasTeoricas: 48, horasPracticas: 0, profesorResponsable: 'Sebastian Carrera', aulaAsignada: '601', prerrequisitos: 'Ninguno', promedioCalificaciones: 3.0},
  {nombreMateria: 'Estructura De Datos I', codigoMateria: 84028, descripcion: 'Curso fundamental en la formación de estudiantes de ciencias de la computación e ingeniería de software, que se centra en la organización y manipulación de datos de manera eficiente.', creditos: 3, horasTeoricas: 0, horasPracticas: 64, profesorResponsable: 'Wilsón Andrés Castillo Castro', aulaAsignada: '603', prerrequisitos: 'Algoritmos Y Programación III', promedioCalificaciones: 3.5},
  {nombreMateria: 'Máquinas Eléctricas', codigoMateria: 84027, descripcion: 'Curso fundamental en la ingeniería eléctrica y en áreas relacionadas que se centra en el estudio de dispositivos que convierten energía eléctrica en energía mecánica o viceversa.', creditos: 3, horasTeoricas: 48, horasPracticas: 0, profesorResponsable: 'Edinson Benavides', aulaAsignada: 'Laboratorio de Fisica', prerrequisitos: 'Electricidad Y Magnetismo', promedioCalificaciones: 3.0},
  {nombreMateria: 'Formulación Y Gestión De Proyectos', codigoMateria: 84038, descripcion: 'Curso que se centra en los principios y técnicas necesarias para planificar, ejecutar y evaluar proyectos de manera efectiva.', creditos: 2, horasTeoricas: 32, horasPracticas: 0, profesorResponsable: 'Wilsón Andrés Castillo Castro', aulaAsignada: '603', prerrequisitos: 'Ninguno', promedioCalificaciones: 3.0},
  {nombreMateria: 'Electrónica Digital', codigoMateria: 84036, descripcion: 'Curso fundamental en el estudio de la ingeniería electrónica y de sistemas, que se centra en los principios y técnicas relacionados con el diseño, análisis y aplicación de circuitos y sistemas digitales.', creditos: 2, horasTeoricas: 0, horasPracticas: 48, profesorResponsable: 'José Javier Villalba Romero', aulaAsignada: 'Laboratorio de Electrónica', prerrequisitos: 'Maquinas Electricas', promedioCalificaciones: 3.5},
  {nombreMateria: 'Estadística Inferencial', codigoMateria: 84035, descripcion: 'Curso que se centra en los métodos y técnicas utilizadas para realizar inferencias o generalizaciones sobre una población a partir de una muestra.', creditos: 3, horasTeoricas: 0, horasPracticas: 48, profesorResponsable: 'Leidy Marcela Gómez Melo', aulaAsignada: '603', prerrequisitos: 'Probabilidad Y Estadística Descriptiva', promedioCalificaciones: 3.5},
  {nombreMateria: 'Teoría De Bases De Datos', codigoMateria: 84033, descripcion: 'Curso fundamental en la formación de estudiantes de informática, ingeniería de software y disciplinas relacionadas.', creditos: 3, horasTeoricas: 48, horasPracticas: 0, profesorResponsable: 'Danny Michael Cardenas Martínez', aulaAsignada: '601', prerrequisitos: 'Ninguno', promedioCalificaciones: 3.0},
  {nombreMateria: 'Procesos De Investigación I', codigoMateria: 84037, descripcion: 'Este curso introduce a los estudiantes a los principios y métodos básicos de la investigación científica.', creditos: 1, horasTeoricas: 32, horasPracticas: 0, profesorResponsable: 'Wilsón Andrés Castillo Castro', aulaAsignada: '601', prerrequisitos: 'Ninguno', promedioCalificaciones: 3.0},
  {nombreMateria: 'Estructura De Datos II', codigoMateria: 84034, descripcion: 'Curso avanzado que se enfoca en el estudio de estructuras de datos más complejas y técnicas de algoritmos utilizados en la programación y el desarrollo de software. ', creditos: 3, horasTeoricas: 0, horasPracticas: 64, profesorResponsable: 'Fabian Parra Pay', aulaAsignada: '604', prerrequisitos: 'Estructura De Datos I', promedioCalificaciones: 3.5},
  {nombreMateria: 'Sistemas Operativos,Configuración Y Uso', codigoMateria: 84044, descripcion: 'Curso que se centra en la comprensión de los sistemas operativos (SO), su arquitectura, funcionamiento y las habilidades necesarias para configurarlos y utilizarlos de manera efectiva.', creditos: 2, horasTeoricas: 32, horasPracticas: 0, profesorResponsable: 'Wilsón Andrés Castillo Castro', aulaAsignada: '603', prerrequisitos: 'Ninguno', promedioCalificaciones: 3.0},
  {nombreMateria: 'Análisis Y Modelamiento De Software', codigoMateria: 84042, descripcion: 'Se centra en la comprensión de las técnicas y metodologías utilizadas para el análisis, diseño y modelado de sistemas de software.', creditos: 2, horasTeoricas: 32, horasPracticas: 0, profesorResponsable: 'Giovanni Albeiro Hernández Pantoja', aulaAsignada: '601', prerrequisitos: 'Ninguno', promedioCalificaciones: 3.0},
  {nombreMateria: 'Visión Empresarial', codigoMateria: 84047, descripcion: 'Curso que se centra en el desarrollo de habilidades y conocimientos necesarios para comprender y formular una visión clara y estratégica dentro de un contexto empresarial.', creditos: 1, horasTeoricas: 32, horasPracticas: 0, profesorResponsable: 'Jorge Arturo Dorado', aulaAsignada: '603', prerrequisitos: 'Ninguno', promedioCalificaciones: 3.0},
  {nombreMateria: 'Procesos De Investigación II', codigoMateria: 84046, descripcion: 'Curso avanzado que se centra en el desarrollo de habilidades y conocimientos necesarios para llevar a cabo investigaciones científicas de manera rigurosa y efectiva.', creditos: 1, horasTeoricas: 32, horasPracticas: 0, profesorResponsable: 'Wilson Andrés Castillo Castro', aulaAsignada: '601', prerrequisitos: 'Procesos De Investigación I', promedioCalificaciones: 3.0},
  {nombreMateria: 'Arquitectura De Computadores Y Organización', codigoMateria: 84043, descripcion: 'Curso que se centra en el estudio de la estructura y funcionamiento de los sistemas computacionales.', creditos: 2, horasTeoricas: 32, horasPracticas: 0, profesorResponsable: 'José Javier Villalba Romero', aulaAsignada: '604', prerrequisitos: 'Ninguno', promedioCalificaciones: 3.0},
  {nombreMateria: 'Simulación', codigoMateria: 84045, descripcion: 'Curso que se centra en el estudio de métodos y técnicas utilizadas para modelar, analizar y simular sistemas complejos en diversas disciplinas, como ingeniería, ciencias sociales, economía y biología.', creditos: 2, horasTeoricas: 32, horasPracticas: 0, profesorResponsable: 'Danny Michael Cardenas Martínez', aulaAsignada: '603', prerrequisitos: 'Ninguno', promedioCalificaciones: 3.0},
  {nombreMateria: 'Práctica De Base De Datos', codigoMateria: 84041, descripcion: 'Curso que se centra en la aplicación práctica de conceptos teóricos relacionados con el diseño, implementación y gestión de bases de datos.', creditos: 3, horasTeoricas: 0, horasPracticas: 48, profesorResponsable: 'Sebastian Carrera', aulaAsignada: '601', prerrequisitos: 'Teoría De Bases De Datos', promedioCalificaciones: 3.5},
  {nombreMateria: 'Ingeniería De Software I', codigoMateria: 84051, descripcion: 'Curso introductorio que se centra en los principios, técnicas y metodologías utilizadas en el desarrollo de software.', creditos: 3, horasTeoricas: 0, horasPracticas: 48, profesorResponsable: 'Giovanni Albeiro Hernández Pantoja', aulaAsignada: '601', prerrequisitos: 'Ninguno', promedioCalificaciones: 3.5},
  {nombreMateria: 'Seminario De Investigación', codigoMateria: 84052, descripcion: 'Curso diseñado para profundizar en las metodologías de investigación y fomentar la capacidad crítica y *****ítica de los estudiantes en el ámbito académico.', creditos: 1, horasTeoricas: 32, horasPracticas: 0, profesorResponsable: 'Wilson Andrés Castillo Castro', aulaAsignada: '602', prerrequisitos: 'Ninguno', promedioCalificaciones: 3.0},
  {nombreMateria: 'Legislación Laboral', codigoMateria: 84053, descripcion: 'Curso que se centra en el estudio de las leyes, normas y regulaciones que rigen las relaciones laborales entre empleadores y empleados.', creditos: 1, horasTeoricas: 32, horasPracticas: 0, profesorResponsable: 'José Javier Villalba Romero', aulaAsignada: '602', prerrequisitos: 'Ninguno', promedioCalificaciones: 3.0},
  {nombreMateria: 'Pilares Del Espíritu Empresarial', codigoMateria: 84054, descripcion: 'Curso que se centra en los fundamentos y valores que impulsan la creación y gestión de empresas exitosas.', creditos: 1, horasTeoricas: 32, horasPracticas: 0, profesorResponsable: 'Jorge Arturo Dorado', aulaAsignada: '407', prerrequisitos: 'Visión Empresarial', promedioCalificaciones: 3.0}
]);

//Busquedas

db.subjects.find({nombreMateria:{$eq:'Algoritmos Y Programación III'}}) //Busca la materia de Algoritmos Y Programación III

//db.subjects.find({creditos:{$gt:2}}) //Busca las materias que tengan créditos mayores que 2

//db.subjects.find({horasTeoricas:{$gte:30}}) //Busca las materias cuyas horas teóricas sean mayores o iguales que 30

//db.subjects.find({horasPracticas:{$lt:40}}) //Busca las materias cuyas horas practicas sean menores a 40

//db.subjects.find({codigoMateria:{$lte:84020}}) //Busca las materias cuyo código sea menor o igual que 84020

//db.subjects.find({profesorResponsable:{$ne:'Leidy Marcela Gómez Melo'}}) //Busca las materias cuyo profesor responsable sea diferente a ella

//db.subjects.find({aulaAsignada:{$in:['602','603']}}) //Busca las materias cuya aula asignada esté en un rango de 602 y 603

//db.subjects.find({creditos:{$nin:[1,3]}}) //Busca las materias que no tengan creditos en un rango de 1 a 3 creditos

//db.subjects.find({profesorResponsable:'Giovanni Albeiro Hernández Pantoja'}) //Busca las materias cuyo profesor responsable sea el profesor Giovanni Hernández

//db.subjects.deleteOne({nombreMateria:'Lectoescritura Investigativa'}) //Elimina de la base de datos la materia especificada